### PR TITLE
Add new validation config

### LINKED ISSUE #49: Apply a label when template validation fails.
When the template fails to validate we could apply a label like `needs-triage` or `needs-more-info`.

Open questions:

- [ ] Should this label name be configurable per repo?  If so, what is the config format?
- [ ] Should this be in addition to the comment or instead of the comment?

### PR DESCRIPTION
**Pull request by samtstern**
Adds a new optional `validation` field to the repo config that looks like this:

```ts
export interface ValidationConfig {
  templates: { [path: string]: TemplateValidationConfig };
}

export interface TemplateValidationConfig {
  validation_failed_label?: string;
  required_section_validation?: "strict" | "relaxed" | "none";
}
```

Example:
```js
validation: {
  templates: {
    ".github/ISSUE_TEMPLATE.md": {
      required_section_validation: "strict",
      validation_failed_label: "validation-failed"
    }
  }
}
```

- `validation_failed_label` is the label that will be added to issues that fail template validation.
- `required_section_validation` lets you set the "REQUIRED" section checker to one of three modes:
  - Strict - all required sections must be filled out.
  - Relaxed - at least one required section must be filled out.
  - None - don't care at all.

Fixes #49

### CODE REVIEW

**Comment by samtstern** [comment]
cc @marcbaechinger does this meet your needs?

**Comment by marcbaechinger** [comment]
Sounds good. Thanks!

Is `required_section_validation` a repo-wide configuration or can it be configured per issue template?

Reason why I am asking is, we are having 4 different templates. Two of which have four required sections. So if we could configure the number of required sections to eg. 2 for these and leave it to a single section for others that would be very useful and leaves some flexibility.

**Comment by samtstern** [comment]
@marcbaechinger per-template sounds like a good idea for all of these, thanks!

**Comment by samtstern** [comment]
@marcbaechinger updated, wdyt about the new format?  Templates are specified by path.

**Comment by samtstern** [comment]
@marcbaechinger quick bump, wdyt?

**Comment by samtstern** [comment]
Ok I am gonna go ahead with this, and we can always change it.

**Pull request merged**
